### ISSUE TITLE
Roadmap to v0.1.0 release

### ISSUE THREAD

**Issue by awrznc** [awrznc/CRyo#3]
## Todo List

- [ ] generate documents.
- [ ] disable generate documents option
- [ ] disable generate tests option

## Not-to-do List

- [ ] module for CMake
